test rerun

diff --git a/.github/workflows/rerun-jetstream.yml b/.github/workflows/rerun-jetstream.yml
--- a/.github/workflows/rerun-jetstream.yml
+++ b/.github/workflows/rerun-jetstream.yml
@@ -4,7 +4,6 @@ on:
   push:
     branches:
       - main
-      - gha-rerun-jetstream # delete me
     paths:
       - 'jetstream/**'
   pull_request: # delete me
@@ -74,7 +73,7 @@ jobs:
         pod_identifier="jetstream-${uuid}"
         echo "Deleting pod [$pod_identifier]"
         echo
-        # kubectl delete pod -l app=$pod_identifier
+        kubectl delete pod -l app=$pod_identifier
         # TODO: deleteme (testing kubectl works)
         kubectl config get-contexts
 
@@ -93,6 +92,7 @@ jobs:
 
           # start a new instance
           # kubectl run $pod_identifier --image=gcr.io/moz-fx-data-experiments/jetstream -l app=$pod_identifier --restart=Never --command -- jetstream rerun --argo --return-status --recreate-enrollments $(echo $params)
+          kubectl run $pod_identifier --image=gcr.io/moz-fx-data-experiments/jetstream -l app=$pod_identifier --restart=Never --command -- jetstream rerun --argo --dataset-id=mwilli_test --zone=us-central1-c --cluster-id=jetstream-dev --return-status --recreate-enrollments $(echo $params)
           # link to logs
           cur_date=`date -u +%FT%TZ`
           echo "Pod Logs: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22moz-fx-data-experiments%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22jetstream%22%0Aresource.labels.namespace_name%3D%22default%22?scrollTimestamp=$cur_date"
@@ -100,32 +100,32 @@ jobs:
           # wait for pod to finish and check status
         fi
 
-        # running=true
+        running=true
         # TODO: changeme
         # running=false
-        # while [ $running = true ]
-        # do
-        #   echo "Wait for jetstream to finish"
-        #   pod_status=`kubectl get pod -l app=$pod_identifier --no-headers -o custom-columns=":status.phase"`
-        #   if [ $pod_status = 'Succeeded' ] || [ $pod_status = 'Failed' ]; then
-        #     running=false
-        #   fi
-        #   sleep 10
-        # done
+        while [ $running = true ]
+        do
+          echo "Wait for jetstream to finish"
+          pod_status=`kubectl get pod -l app=$pod_identifier --no-headers -o custom-columns=":status.phase"`
+          if [ $pod_status = 'Succeeded' ] || [ $pod_status = 'Failed' ]; then
+            running=false
+          fi
+          sleep 10
+        done
         # delete pod
         echo "Deleting pod [$pod_identifier]"
         echo
-        # kubectl delete pod -l app=$pod_identifier
-        # if [ $pod_status = 'Failed' ]; then
-        #   echo "Error when running jetstream. Check the logs for more information."
-        #   exit 1
-        # elif [ $pod_status = 'Succeeded' ]; then
-        #   echo "Jetstream successfully completed."
-        # else
-        #   echo "Jetstream completed in unknown status. Please check the logs."
-        #   echo "Analysis Errors can be accessed via Looker: https://mozilla.cloud.looker.com/dashboards/246"
-        #   exit 1
-        # fi
+        kubectl delete pod -l app=$pod_identifier
+        if [ $pod_status = 'Failed' ]; then
+          echo "Error when running jetstream. Check the logs for more information."
+          exit 1
+        elif [ $pod_status = 'Succeeded' ]; then
+          echo "Jetstream successfully completed."
+        else
+          echo "Jetstream completed in unknown status. Please check the logs."
+          echo "Analysis Errors can be accessed via Looker: https://mozilla.cloud.looker.com/dashboards/246"
+          exit 1
+        fi
         
         # TODO: deleteme
         exit 1
