feat: add pr warnings for high data processing

diff --git a/.github/workflows/validate-jetstream.yml b/.github/workflows/validate-jetstream.yml
--- a/.github/workflows/validate-jetstream.yml
+++ b/.github/workflows/validate-jetstream.yml
@@ -53,13 +53,18 @@ jobs:
         GOOGLE_GHA_ID_TOKEN: ${{ steps.auth.outputs.id_token }}
       run: echo "GOOGLE_GHA_ID_TOKEN=$GOOGLE_GHA_ID_TOKEN" >> $GITHUB_ENV
     - name: Validate jetstream config files
+      id: validate_jetstream
+      continue-on-error: true
       env:
         ALL_CHANGED_FILES: ${{ needs.changed.outputs.all_changed_files }}
+      # set +e allows this step to continue past the jetstream command even with a nonzero exit code
       run: |
+        set +e
         echo "Run validation on changed files: "
         echo $ALL_CHANGED_FILES
         echo "jetstream validate_config --config_repos='.' --config_repos=jetstream/ $ALL_CHANGED_FILES"
         jetstream validate_config --config_repos='.' --config_repos=jetstream/ $ALL_CHANGED_FILES
+        echo "JETSTREAM_EXIT_CODE=$?" >> $GITHUB_ENV
     - uses: actions/github-script@v6
       if: ${{ github.event_name == 'pull_request' && success() }}
       with:
@@ -70,6 +75,32 @@ jobs:
             repo: context.repo.repo,
             issue_number: context.issue.number,
             body: "✅ Jetstream Validation is complete. Check the CI logs for this step for **Query SQL** and **data processing estimates**."
+          })
+    - uses: actions/github-script@v6
+      if: ${{ github.event_name == 'pull_request' && "$JETSTREAM_EXIT_CODE" == "2"}}
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          github.rest.issues.createComment({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            issue_number: context.issue.number,
+            body: "⚠️ Experiment metrics query data processing estimate exceeded moderate threshold.
+            
+            Check logs to confirm query SQL."
+          })
+    - uses: actions/github-script@v6
+      if: ${{ github.event_name == 'pull_request' && "$JETSTREAM_EXIT_CODE" == "3"}}
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          github.rest.issues.createComment({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            issue_number: context.issue.number,
+            body: "❗ Experiment metrics query data processing estimate exceeded high threshold and may fail.
+            
+            Updating the configuration is recommended."
           })
 
 
